### ISSUE TITLE
Are spec dependencies assumed to be pinned?

### ISSUE THREAD

**Issue by michielbdejong** [solid/solid-oidc#197]
Version 0.9.0 of https://solidproject.org/TR/protocol was last modified on 17 December, but if you follow the [link from there](https://solidproject.org/TR/protocol#bib-solid-oidc) to the Solid OIDC spec, that is an unversioned link to https://solid.github.io/solid-oidc/

That document claims to have been created on 28 April which is odd in itself because on 13 December https://github.com/solid/solid-oidc/tree/a5a966c7342da01a57bfb316e5533ea7d82fd245 already pointed to it. In any case, it seems likely that at the time of publishing, version 0.9.0 of the spec pointed to [this version of Solid OIDC](https://github.com/solid/solid-oidc/blob/a5a966c7342da01a57bfb316e5533ea7d82fd245/index.bs), which in turn [points to](https://github.com/solid/solid-oidc/blob/a5a966c7342da01a57bfb316e5533ea7d82fd245/index.bs#L480) version 4 of the DPoP id.

Readers who read version 0.9.0 of the Solid spec nowadays, and follow their nose, end up at https://solid.github.io/solid-oidc/#normative which points to DPoP [without choosing any particular version](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop).

In software development it's common practice to pin dependencies when publishing. This prevents things from breaking at random unexpected times, and allows the publisher to update dependencies in a controlled way. Should we do the same in spec development?

**Comment by csarven** [comment]
I believe the dates of the Solid-OIDC ED: https://solid.github.io/solid-oidc/ , should be as suggested as in https://github.com/solid/solid-oidc/issues/105#issuecomment-1103283231, in particular:

>ED/oidc
>* Created: 2021-07-16 (whenever it came to existence)
>* Published: 2021-07-16 (usually same as created...)
>* Modified: 2022-04-30 (update as you go)
>
>Note that above I used the date from gh-page's first commit - assuming everything else was configured for https://solid.github.io/solid-oidc/

**Comment by elf-pavlik** [comment]
Since FPWD was released to https://solidproject.org/TR/oidc no releases should point anymore to the ED.

@michielbdejong any version release of Solid-OIDC will be now processed with this github workflow https://github.com/solid/solid-oidc/blob/main/.github/workflows/tr-draft-config.yml

There result will go as PR to https://github.com/solid/specification

**Comment by csarven** [comment]
>Since FPWD was released to https://solidproject.org/TR/oidc no releases should point anymore to the ED.

That is at the discretion of the authors making the citation.

TR/protocol as of this writing refers to Solid-OIDC ED, and ED/protocol (will eventually make it into the next update of TR/protocol) refers to TR/oidc. The Solid-OIDC ED dates should be corrected irrespective to any of that.

**Comment by acoburn** [comment]
Just as in software development, when referencing a "snapshot dependency" (in this case, that would be an editor's draft), you need to be aware that this dependency may change at any time.

It is true that Solid Protocol 0.9 points to the editor's draft of Solid OIDC, which means that the dependency is not fixed.
You will also note that the published [Solid-OIDC 0.1](https://solidproject.org/TR/2022/oidc-20220328) document depends on the [draft DPoP specification](https://datatracker.ietf.org/doc/html/draft-ietf-oauth-dpop) (which also continues to change)

Obviously, it is better for a published specification to always depend on other non-draft published specifications, but that is not always possible. (WebID has been in draft since 2005). In this case, if the dependency is a draft, there is an implicit acknowledgement that the dependency is not fixed

**Comment by elf-pavlik** [comment]
> In software development it's common practice to pin dependencies when publishing. This prevents things from breaking at random unexpected times, and allows the publisher to update dependencies in a controlled way. Should we do the same in spec development?

@michielbdejong described workflow, starting from Solid-OIDC 0.1, satisfy your suggestion?

> The Solid-OIDC ED dates should be corrected irrespective of any of that.

@csarven could you please submit a PR that corrects the dates?
Otherwise at least please explain here which exact dates you would like to be changed, including expected values.

**Comment by csarven** [comment]
Update created and add published. See the suggested values as mentioned in https://github.com/solid/solid-oidc/issues/197#issuecomment-1263461771.

**Comment by michielbdejong** [comment]
> if the dependency is a draft, there is an implicit acknowledgement that the dependency is not fixed

That answers my question, thanks!
