### ISSUE TITLE
"Modified" date is misleading

### ISSUE THREAD

**Issue by VirginiaBalseiro** [solid/solid-oidc#233]
The page at https://solid.github.io/solid-oidc/ shows a "Modified" date, which is currently listed as April 15. I expected this date to reflect changes or updates in the content. However, it appears that the date is automatically updated with every commit, even when the commits are only related to dependency updates. For instance, on April 15, the only commits made were related to dependency updates.

I believe that the "Modified" date should only be updated when there are actual changes to the content. This would provide a more accurate reflection of when the content was last modified.

**Comment by elf-pavlik** [comment]
This is an editor's draft, which I consider primarily relevant for active participants. The broader audience should rely on the latest published versions where the data would reflect when it was published.

Do you see a specific, pragmatic problem with the editor's draft having a date of the last commit?

**Comment by acoburn** [comment]
From a purely practical perspective, what @VirginiaBalseiro describes is not possible with the current structure.

This specification uses BikeShed, and the modification date is updated every time HTML is rendered from the BikeShed source. That rendering happens on every commit, whether that commit changes the contents of the document or whether we update the version of Python that run in GH actions. But either way, we _definitely_ want that rendering to happen at each commit, since that is how we ensure that the editor's version is an accurate reflection of the source data.

I would advocate closing this issue.

**Comment by VirginiaBalseiro** [comment]
> Do you see a specific, pragmatic problem with the editor's draft having a date of the last commit?

Like I said, I find it confusing that the date does not reflect changes in content, but not a dealbreaker, just a suggestion.
