### ISSUE TITLE
Accessing NonRDF-Sources directly via browser

### ISSUE THREAD

**Issue by elf-pavlik** [solid/solid-oidc#31]
In most cases users will access RDF-Sources using some specialized client application. In that case we will have user delegating access to that application (authorize it).
In some cases user may access NonRDF-Sources directly with a web browser. For example to download some binary archive, or view static html page which may include some images.
In that case I don't see where current WebID-OIDC would fit. For downloading binary files, one could still use some client application instead of navigating browser to download like directly. But to access WAC protected static html pages which include some images, one would not use some 'nested web browser' client.
I wonder how everyone see accessing WAC protected static HTML pages with some other static assets, all NonRDF-Sources.

**Comment by elf-pavlik** [comment]
As discussed today we are circulating this issue with the solid protocol https://github.com/solid/specification/issues/382

**Comment by woutermont** [comment]
Hadn't seen this issue before. I'm wondering: up till now the RS could be purely backend; enabling browser access to non-rdf resources forces implementations to provide a front-end as well... This complicates things quite a bit i.m.o. Is this a case where we want to put this burden on the implementers to accomodate to the users?

**Comment by acoburn** [comment]
@woutermont 

> This complicates things quite a bit i.m.o. Is this a case where we want to put this burden on the implementers to accomodate to the users?

You are exactly right that this complicates things.

From my perspective, I really don't think this would be a _requirement_ on server implementers. In fact, I would argue _against_ requiring such a feature. 

However, there are servers that will implement this pattern, and with that in mind, I think it would be beneficial to have some documented implementation patterns and security considerations precisely so that each server implementer (those that _do_ wish to implement this) can leverage some community insight in that process.

**Comment by elf-pavlik** [comment]
Solid-OIDC doesn't need to address it. Discussion can be continued in https://github.com/solid/specification/issues/382
