### ISSUE TITLE
Clarify what the issuer URL is

### ISSUE THREAD

**Issue by RubenVerborgh** [solid/solid-oidc#38]
The text currently reads under https://solid.github.io/solid-oidc/#tokens-access:

> iss — The issuer claim MUST be a valid URL of the IdP instantiating this token.

And the example is

```
    "iss": "https://idp.example.com",
```

However, as remarked by @acoburn, https://openid.net/specs/openid-connect-core-1_0.html#IssuerIdentifier says:

> The issuer returned by discovery MUST exactly match the value of iss in the ID Token.

and

> It is RECOMMENDED that only a single Issuer per host be used. However, if a host supports multiple tenants, multiple Issuers for that host may be needed.

So what is the exact URL that we will mandate?

**Comment by acoburn** [comment]
The URL is whatever the discovery document says it is. IOW, when you take the iss claim and append .well-known/openid-configuration, that JSON document will have an issuer claim. The two need to be exact string matches.

Some valid examples include:

https://idp.example
https://idp.example/
https://idp.example/tenant
https://idp.example/tenant/

**Comment by RubenVerborgh** [comment]
Thanks. That's a suffient clarification to me; I wonder if perhaps a short note in the doc could help.

**Comment by elf-pavlik** [comment]
https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

> If the Issuer value contains a path component, any terminating `/` MUST be removed before appending `/.well-known/openid-configuration`.

-----------

> I wonder if perhaps a short note in the doc could help.

I recall in gitter there was a discussion about verifying if issuer in Access Token is the one designated by the user. Current draft says:

> If the iss claim is different from the domain of the WebID, then the RS MUST check the WebID document for the existence of a statement matching ?webid <http://www.w3.org/ns/solid/terms#oidcIssuer> ?iss., where ?webid and ?iss are the values of the webid and iss claims respectively.

Should we add that `iss` IRI is matched using [Simple String Comparision](https://datatracker.ietf.org/doc/html/rfc3987#section-5.3.1)

**Comment by elf-pavlik** [comment]
I think we could reference this section: https://datatracker.ietf.org/doc/html/rfc8414#section-3.1

> If the issuer identifier value contains a path component, any
   terminating "/" MUST be removed before inserting "/.well-known/" and
   the well-known URI suffix between the host component and the path
   component.  The client would make the following request when the
   issuer identifier is "https://example.com/issuer1" and the well-known
   URI suffix is "oauth-authorization-server" to obtain the metadata,
   since the issuer identifier contains a path component:
   ```
     GET /.well-known/oauth-authorization-server/issuer1 HTTP/1.1
     Host: example.com
   ```
> Using path components enables supporting multiple issuers per host.
   This is required in some multi-tenant hosting configurations.  This
   use of ".well-known" is for supporting multiple issuers per host;
   unlike its use in RFC 5785 [RFC5785], it does not provide general
   information about the host.

**Comment by elf-pavlik** [comment]
> Should we add that both webid and iss IRIs are matched using [Simple String Comparision](https://datatracker.ietf.org/doc/html/rfc3987#section-5.3.1)

I think we should actually recommend normalizing the issuer IRI before trying to match it.

This comes especially important for authority with an empty path. Since `https://op.example` is equivalent to `https://op.example/`, the issuer check MUST not fail due to this difference.

https://www.rfc-editor.org/rfc/rfc3986#section-6.2.3

**Comment by acoburn** [comment]
Normalizing the URL is getting into dangerous territory. OpenID and OAuth have historically replied on String comparisons for this. You can see this in the spec references above. I would highly, highly recommend not doing anything different for Solid.

**Comment by elf-pavlik** [comment]
I see, I'll look into adding a NOTE that mentions the normalization topic and warns that that `https://op.example/` and `https://op.example` fail simple string comparison even though they are equivalent IRIs.

In the end, direct user input is not being compared, only the information in the Id Token and WebID document.
If the user has to edit their WebID Document on their own, they should be warned to use the exact same value that OP provided to them.
